### ISSUE TITLE
metacall cli install mac error

### ISSUE THREAD

**Issue by niranjanaryan** [metacall/install#17]
▷ Start to download the tarball.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
✘ The tarball metacall-tarball-osx-amd64.tar.gz could not be downloaded.
  Please, refer to https://github.com/metacall/install/issues and create a new issue.
  Aborting installation.
‼ Binary installation has failed, fallback to Docker installation.

**Comment by viferga** [comment]
MacOS support is not fully implemented yet, if you want to help check out this repository: https://github.com/metacall/distributable-macos/issues

In the issues there is some listed approaches that we may use for implementing it.

**Comment by viferga** [comment]
@niranjanaryan Now MacOS is fully supported, for intel and arm architectures. You can test it out.
