### ISSUE TITLE
PYTHONPATH and other environment variables are not properly set

### ISSUE THREAD

**Issue by viferga** [metacall/install#2]
Once them are provided from: https://github.com/metacall/distributable/issues/4
Update them in the install script.

**Comment by pkspyder007** [comment]
To solve this issue

1 -> Reinstall everything

2-> open this script /usr/local/bin/metacall in any editor

3-> add this on 2nd line of the script `export PYTHONPATH=/gnu/store/q9rm8h9imazsq2c4qiv2yjpvlvliywqb-python-3.8.2/lib`

4 -> Restart everything

If the error still persists please ask us in the discord, there might be some specific issue your system

**Comment by viferga** [comment]
This issue is solved with a workaround, for more information: https://github.com/metacall/distributable/issues/4#issuecomment-820432394
