### ISSUE TITLE
Installation Freezing Issue on Windows

### ISSUE THREAD

**Issue by Khushal-Pabri** [metacall/install#22]
### When using the provided PowerShell command for installation:

```powershell
powershell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/metacall/install/master/install.ps1')))"
```

I encountered a freezing issue where nothing happens during the installation process.

### Temporary Fix:
I found a workaround by explicitly setting the TLS version to 1.2 using the following PowerShell command:
```powershell
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```
After executing this command, the installation script worked as expected.

### Reverting to System Default:
To set the [Net.ServicePointManager]::SecurityProtocol back to the system default, you can use the following PowerShell command:

```powershell
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::SystemDefault
```
This ensures that the TLS version is back to the default configuration on your system.

**Comment by viferga** [comment]
I can't reproduce it and the security protocol is already set up in the install command line you pasted at the beginning.
