### ISSUE TITLE
Trigger `metacall/cli` build before testing docker fallback

### ISSUE THREAD

**Issue by viferga** [metacall/install#26]
We should implement something like this step: https://github.com/metacall/distributable-linux/blob/0145dbf442b82064b744ecd558ce51635dcceea4/.github/workflows/post-release.yml#L15

Before the test run, so we have the latest CLI image updated before running the docker fallback tests.

**Comment by SaranshBaniyal** [comment]
Hi @viferga, I would like to contribute to this issue, I have recently explored github actions in my last internship and this issue seems quite relevant and fascinating to me. Looking forward to your response.

**Comment by viferga** [comment]
> Hi @viferga, I would like to contribute to this issue, I have recently explored github actions in my last internship and this issue seems quite relevant and fascinating to me. Looking forward to your response.

You can do the PR whenever you want. Here is the CI you have to trigger: https://github.com/metacall/cli/blob/master/.github/workflows/docker-hub.yml
